language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="f7462f24-c7e8-4dca-ae87-c3dee5ec89d3"

services:
  - postgresql

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -rpegorov@icloud.com
    on_success: never # default: change
    on_failure: always # default: always